name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main", "master"]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # 1) Isometric commit calendar
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: svg/metrics.plugin.isocalendar.svg
          base: ""

          plugin_isocalendar: yes

      # 2) Comment reactions
      - uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage

      # 3) Wakatime
      - uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

      # Commit
      - name: Commit generated metrics
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update metrics"
          file_pattern: "svg/*.svg"